### ISSUE TITLE
Trace information is scarce. Unable to troubleshoot output issues.

### ISSUE THREAD

**Issue by vosdev** [fluent/fluent-bit#1942]
## Bug Report

**Describe the bug**

My fluentbit (td-agent-bit) fails to flush chunks: `[engine] failed to flush chunk '3743-1581410162.822679017.flb', retry in 617 seconds: task_id=56, input=systemd.1 > output=es.0`. This is the only log entry that shows up. Trace logging is enabled but there is no log entry to help me further.

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
[2020/02/11 10:21:23] [trace] [thread 0x7f3b1c59bf50] created (custom data at 0x7f3b1c59bf78, size=64
[2020/02/11 10:21:23] [trace] [thread 0x7f3b1c59bee0] created (custom data at 0x7f3b1c59bf08, size=64
[2020/02/11 10:21:28] [trace] [engine] [task event] task_id=56 thread_id=3 return=RETRY
[2020/02/11 10:21:28] [debug] [retry] re-using retry for task_id=56 attemps=4
[2020/02/11 10:21:28] [trace] [thread] destroy thread=0x7f3b4cc7bad0 data=0x7f3b4cc7baf8
[2020/02/11 10:21:28] [ warn] [engine] failed to flush chunk '3743-1581410162.822679017.flb', retry in 617 seconds: task_id=56, input=systemd.1 > output=es.0
[2020/02/11 10:21:28] [trace] [task 0x7f3b1fdfe8a0] created (id=485)
[2020/02/11 10:21:28] [debug] [task] created task=0x7f3b1fdfe8a0 id=485 OK
[2020/02/11 10:21:28] [trace] [thread 0x7f3b1c59be70] created (custom data at 0x7f3b1c59be98, size=64
[2020/02/11 10:21:33] [trace] [thread 0x7f3b1c59bd90] created (custom data at 0x7f3b1c59bdb8, size=64
```
- Steps to reproduce the problem:

**Expected behavior**
An actual message containing information about what goes wrong.

**Screenshots**

**Your Environment**

* Version used: 1.3.7
* Configuration: 
```
[SERVICE]
    Flush        5
    Daemon       Off
    Log_Level    trace
    Parsers_File parsers.conf
    Plugins_File plugins.conf
    HTTP_Server  Off
    HTTP_Listen  0.0.0.0
    HTTP_Port    2020

[INPUT]
    Name tail
    Tag nginx
    Interval_Sec 1
    Path    /var/log/nginx/*

[INPUT]
    Name systemd
    Tag journald
    Interval_Sec 1

[OUTPUT]
    Name es
    Match *
    Host es1.example.com
    Port 9200
    Index fluentbit
    Retry_Limit False
    Type  _doc
```

* Operating System and version: Ubuntu 18.04 fully up to date, td-agent-bit latest version
* Filters and plugins: Default package, no additional plugins.

**Additional context**

I am trying to have fluentbit process and ship logs to my (IPv6 only) elasticsearch cluster.
Firewall is not a problem here. Filebeat from the same VM is able to connect to my elasticsearch ingest node over the same port.
Tracking connections on my es1.example.com shows that there is no incoming connections from my VM on port 9200.

**Comment by acarsercan** [comment]
same here, running 1.3.7

**Comment by b4stien** [comment]
Same problem here, running 1.3.9.

**Config**

```
[SERVICE]
    Flush        5
    Daemon       Off
    Log_Level    trace
    Parsers_File parsers.conf
    Plugins_File plugins.conf
    HTTP_Server  Off
    HTTP_Listen  0.0.0.0
    HTTP_Port    2020

[INPUT]
    Name cpu
    Tag  cpu.local
    Interval_Sec 1

[OUTPUT]
    Name  stackdriver
    Match *
    google_service_credentials /home/ubuntu/gcp-logs-service-account.json
    resource gce_instance
```

**Log**
```
[2020/02/27 13:39:57] [ warn] [engine] failed to flush chunk '6027-1582810794.326935.flb', retry in 11 seconds: task_id=0, input=cpu.0 > output=stackdriver.0
```

**Comment by danischroeter** [comment]
Same here, running 1.3.7 with tail in and elasticsearch out...
```
[2020/03/03 14:28:45] [ info] [sp] stream processor started
Mar 03 14:28:50 chtkj143.scaling.ch td-agent-bit[68370]: [2020/03/03 14:28:50] [ warn] [engine] failed to flush chunk '68370-1583242125.632891683.flb', retry in 6 seconds: task_id=3, input=tail.1 > output=es.1
[2020/03/03 14:28:50] [ warn] [engine] failed to flush chunk '68370-1583242125.565091701.flb', retry in 7 seconds: task_id=2, input=tail.1 > output=es.1
[2020/03/03 14:28:50] [ warn] [engine] failed to flush chunk '68370-1583242125.63632033.flb', retry in 11 seconds: task_id=0, input=systemd.0 > output=es.1
[2020/03/03 14:28:50] [ warn] [engine] failed to flush chunk '68370-1583242125.250399917.flb', retry in 8 seconds: task_id=1, input=tail.1 > output=es.1
[2020/03/03 14:28:56] [ warn] [engine] chunk '68370-1583242125.632891683.flb' cannot be retried: task_id=3, input=tail.1 > output=es.1
```

So far this only happens after restarting td-agent-bit. But might be because of the initial load...

**Comment by danischroeter** [comment]
In my case the problem got visible when enabling debug log:
```
 [debug] [out_es] HTTP Status=413 URI=/_bulk
 [debug] [retry] new retry created for task_id=2 attemps=1
[2020/03/03 15:20:26] [ warn] [engine] failed to flush chunk '95175-1583245223.91940987.flb', retry in 8 seconds: task_id=2, input=tail.1 > output=es.1
```
So we needed to change the allowed body size for those elasticsearch posts and now its working fine...

**Comment by krucelee** [comment]
@danischroeter could you please share more info for your updates?

**Comment by danischroeter** [comment]
@krucelee in my case log debug showed that the elasticsearch output was not able to send big post requests. When we fixed that everything worked like a charm... So my issue might or might not be related to this issue - but the problems visible in the log look exactly the same...
hope that helps...

**Comment by Pointer666** [comment]
@danischroeter How did you fix that? Was it a configuration issue in elasticsearch?

**Comment by danischroeter** [comment]
@Pointer666 Elasticsearch itself accepts pretty big documents so no. We have a loadbalancer in the way that accepted only 1MB of data. (maxBodySize)

**Comment by msvbhat** [comment]
I'm seeing same issue with `Fluent Bit v1.4.2`

For us there is no LB between fluentbit and ES. The debug/trace output even prints HTTP 200OK. But I still get the warning message. And I also I don't see logs in ES.

**Comment by debu99** [comment]
same issue here, enable debug shows "[error] [io] TCP connection failed: 10.104.11.198:9200 (Connection timed out)" but the es is connectable under curl

**Comment by tirelibirefe** [comment]
yes, it doesn't work.

```
  output-elasticsearch.conf: |
    [OUTPUT]
        Name            es
        Match           *
        Host            ${FLUENT_ELASTICSEARCH_HOST}
        Port            ${FLUENT_ELASTICSEARCH_PORT}
        Logstash_Format On
        Replace_Dots    On
        Retry_Limit     False
        tls On
        tls.verify Off
```

**Comment by pavdmyt** [comment]
Having similar issue at versions `1.3.7` and `1.4.6` (running in kubernetes from image [fluent/fluent-bit](https://hub.docker.com/r/fluent/fluent-bit)), trying to write directly (w\o any LBs) into Elasticsearch:

```
[2020/07/02 16:58:49] [ warn] [engine] failed to flush chunk '1-1593708600.190137070.flb', retry in 10 seconds: task_id=412, input=forward.0 > output=es.0
[2020/07/02 16:58:50] [ warn] [engine] failed to flush chunk '1-1593708362.110469660.flb', retry in 1747 seconds: task_id=381, input=forward.0 > output=es.0
[2020/07/02 16:58:52] [ warn] [engine] failed to flush chunk '1-1593705332.363925860.flb', retry in 1648 seconds: task_id=220, input=forward.0 > output=es.0
```

The output configuration is as follows:

```
[OUTPUT]
    Name                 es
    Match                *
    Host                 elasticsearch
    Port                 9200
    Logstash_Format      Off
    Retry_Limit          False
    Type                 cloud
    Time_Key             @timestamp
    Replace_Dots         Off
    Index                fluentd-foo-%Y%m%d
    Buffer_Size          False
    Generate_ID          True
    Current_Time_Index   True
```

Service configuration (just in case):

```
[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info
    HTTP_Server  On
    HTTP_Listen  0.0.0.0
    HTTP_Port    2020
```

Also, sometimes there are following messages:

```
[2020/07/02 16:50:37] [ warn] [pack] invalid UTF-8 bytes, skipping
```

Maybe it somehow causing chunk flush failures?

**Comment by salanki** [comment]
Same here. Kubernetes with ES, no LB.

**Comment by nicon89** [comment]
Same here, debug log shows:
`[2020/07/31 09:49:04] [debug] [output:es:es.0] HTTP Status=200 URI=/_bulk                                                                                                                                  [2020/07/31 09:49:04] [debug] [upstream] KA connection #43 to hostname.es.amazonaws.com:443 is now available
[2020/07/31 09:49:04] [debug] [retry] re-using retry for task_id=1 attemps=4                                                                                                                               [2020/07/31 09:49:04] [ warn] [engine] failed to flush chunk '1-1596188824.323061089.flb', retry in 296 seconds: task_id=1, input=tail.0 > output=es.0`

**Comment by jseiser** [comment]
same issue here.  

```
[2020/08/11 19:12:42] [ warn] [engine] failed to flush chunk '1-1597168718.180690724.flb', retry in 1826 seconds: task_id=1255, input=tail.0 > output=es.11
[2020/08/11 19:12:42] [ warn] [engine] failed to flush chunk '1-1597160787.50225250.flb', retry in 1302 seconds: task_id=178, input=tail.0 > output=es.11
[2020/08/11 19:12:42] [ warn] [engine] failed to flush chunk '1-1597171658.172930023.flb', retry in 1069 seconds: task_id=1678, input=tail.0 > output=es.11
[2020/08/11 19:12:44] [ warn] [engine] failed to flush chunk '1-1597163708.170632477.flb', retry in 1506 seconds: task_id=587, input=tail.0 > output=es.11
[2020/08/11 19:12:44] [ warn] [engine] failed to flush chunk '1-1597171198.168403261.flb', retry in 135 seconds: task_id=1605, input=tail.0 > output=es.11
[2020/08/11 19:12:45] [ warn] [engine] failed to flush chunk '1-1597173158.168320743.flb', retry in 17 seconds: task_id=1890, input=tail.0 > output=es.11
[2020/08/11 19:12:46] [ warn] [engine] failed to flush chunk '1-1597167138.171889813.flb', retry in 1460 seconds: task_id=1044, input=tail.0 > output=es.11
```

Errors continue until you kill the pod and have it restart.

**Comment by vasudeva78** [comment]
Deleting Logstash_Format  On in [OUTPUT] section made fluent-bit flush messages to ES.

**Comment by CadenGuo** [comment]
Same issue here, using fluent-bit v1.4.1 and elasticsearch 6.7.0 in kubernetes. No LB in between.
```
[2020/09/15 03:17:05] [ warn] [engine] failed to flush chunk '1-1600139822.506829797.flb', retry in 9 seconds: task_id=1, input=tail.0 > output=es.0
[2020/09/15 03:17:06] [ warn] [engine] failed to flush chunk '1-1600139821.545999204.flb', retry in 10 seconds: task_id=2, input=tail.0 > output=es.0
[2020/09/15 03:17:07] [ warn] [engine] failed to flush chunk '1-1600139805.701902977.flb', retry in 8 seconds: task_id=5, input=tail.0 > output=es.0
[2020/09/15 03:17:13] [ warn] [engine] failed to flush chunk '1-1600139816.353403854.flb', retry in 59 seconds: task_id=3, input=tail.0 > output=es.0
[2020/09/15 03:17:15] [ warn] [engine] failed to flush chunk '1-1600139805.701902977.flb', retry in 21 seconds: task_id=5, input=tail.0 > output=es.0
[2020/09/15 03:17:18] [ warn] [engine] failed to flush chunk '1-1600139835.832989106.flb', retry in 6 seconds: task_id=4, input=tail.0 > output=es.0
```

These warnings will show up about every 10-20 minutes. But several minutes later, these failed chunks will be flushed successfully.
```
[2020/09/15 03:18:11] [ info] [engine] flush chunk '1-1600139872.118995746.flb' succeeded at retry 1: task_id=1, input=tail.0 > output=es.0
[2020/09/15 03:18:12] [ info] [engine] flush chunk '1-1600139816.353403854.flb' succeeded at retry 2: task_id=2, input=tail.0 > output=es.0
[2020/09/15 03:18:18] [ info] [engine] flush chunk '1-1600139885.964481384.flb' succeeded at retry 1: task_id=1, input=tail.0 > output=es.0
[2020/09/15 03:18:21] [ info] [engine] flush chunk '1-1600139885.973474153.flb' succeeded at retry 1: task_id=1, input=tail.0 > output=es.0
[2020/09/15 03:18:32] [ info] [engine] flush chunk '1-1600139841.840331430.flb' succeeded at retry 2: task_id=2, input=tail.0 > output=es.0
[2020/09/15 03:33:13] [ info] [engine] flush chunk '1-1600139811.103477771.flb' succeeded at retry 3: task_id=3, input=tail.0 > output=es.0
```

**Comment by helicase-bzh** [comment]
Hi,
I had the same issue, i updated to 1.5.7, but no change.
After 30 min, no data are pull up on ES.
but if i remove kubernetes filter it's OK.
any ideas,
ty

**Comment by alejandroEsc** [comment]
Hi there, I was seeing this on my fluentbit intances as well. How we resolved this is by changing the `OUTPUT: Retry_Limit 10` or lower and balance that with `INTPUT: Buffer_Max_Size` that should help keeping the buffer filled with items to retry.

**Comment by tillepille** [comment]
@alejandroEsc Do you have a guidance value for the `Buffer_Max_Size`? 

I was running into the same issue today as well...
Running fluent bit 1.6.4

**Comment by DavidWittman** [comment]
In my case, this was happening because I had some fields in my logs with the same name but of different types, and Elasticsearch was rejecting them. E.g.

``` json
{"ids": [123, 456]}
{"ids": [{"foo": 123, "bar": 456}]}
```

**Comment by edsiper** [comment]
The original issue is a IPv6 problem. The workaround is to enable ```ipv6 on``` in the output configuration section.

Starting from Fluent Bit v1.7 this is handled automatically, so if a DNS returns ipv4 or ipv6 addresses it will work just fine, no manual config will be required.

Closing since this is fixed in c40c1e26eae100084d0747854c1c2a632d07a6cc (GIT master)

**Comment by cokegen** [comment]
`Trace_Error On` + `Log_Level debug` helped me in diagnosing my issue, which was related to ES reaching a limit for `cluster.max_shards_per_node`.

Thanks @DavidWittman

**Comment by sagarkal** [comment]
In my case, the issue was that I had specified **tls** as **on** in the tail input config. But the Elasticsearch was not supporting TLS. Once I specified **tls** as **off** in the tail input config, my logs started getting dispatched to Elasticsearch.
