### ISSUE TITLE
v1.5.7 - SIGSEGV & stack smashing detected

### ISSUE THREAD

**Issue by epcim** [fluent/fluent-bit#2652]
## Bug Report

**Fluentbit freq. crash short after start**

- on cluster with 10 nodes, 3 nodes affected, other started and without restart runs > 20h.
- the three nodes affected, failed 17x, 57x, 142x, then started and holds functional

- any recent changes on fluentbit made on k8s integration?
- I see `flb_upstream` but `[UPSTREAM]` is not configured in config at all..

```
Fluent Bit v1.5.7
* Copyright (C) 2019-2020 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2020/10/07 08:17:00] [ info] [engine] started (pid=6)
[2020/10/07 08:17:00] [ info] [storage] version=1.0.5, initializing...
[2020/10/07 08:17:00] [ info] [storage] in-memory
[2020/10/07 08:17:00] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2020/10/07 08:17:00] [ info] [input:forward:forward.0] listening on 0.0.0.0:65011
[2020/10/07 08:17:00] [ info] [input:systemd:systemd.1] seek_cursor=s=2323c187d3894bdeaedc7b34732c3790;i=f9f... OK
[2020/10/07 08:18:34] [ info] [filter:throttle:throttle.0] 1602058714: limit is 40000.00 per 60s with window size of 5, current rate is: 0 per interval
[2020/10/07 08:18:34] [ info] [filter:kubernetes:kubernetes.1] https=1 host=kubernetes.default.svc.cluster.local port=443
[2020/10/07 08:18:34] [ info] [filter:kubernetes:kubernetes.1] local POD info OK
[2020/10/07 08:18:34] [ info] [filter:kubernetes:kubernetes.1] testing connectivity with API server...
[engine] caught signal (SIGSEGV)
#0  0x5027a8            in  flb_io_net_connect() at src/flb_io.c:360
#1  0x4eb83e            in  create_conn() at src/flb_upstream.c:263
#2  0x4ebc7a            in  flb_upstream_conn_get() at src/flb_upstream.c:387
#3  0x57fa76            in  get_api_server_info() at plugins/filter_kubernetes/kube_meta.c:213
#4  0x582388            in  flb_kube_meta_init() at plugins/filter_kubernetes/kube_meta.c:1002
#5  0x57d14f            in  cb_kube_init() at plugins/filter_kubernetes/kubernetes.c:199
#6  0x4d9b9f            in  flb_filter_init_all() at src/flb_filter.c:431
#7  0x4e54c8            in  flb_engine_start() at src/flb_engine.c:458
#8  0x44817a            in  flb_main() at src/fluent-bit.c:1035
#9  0x4481c8            in  main() at src/fluent-bit.c:1048
#10 0x7fda5c8fa83f      in  ???() at ???:0
#11 0x445cf8            in  ???() at ???:0
#12 0xffffffffffffffff  in  ???() at ???:0
```

another case

```
Fluent Bit v1.5.7
* Copyright (C) 2019-2020 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2020/10/07 04:53:02] [ info] [engine] started (pid=6)
[2020/10/07 04:53:02] [ info] [storage] version=1.0.5, initializing...
[2020/10/07 04:53:02] [ info] [storage] in-memory
[2020/10/07 04:53:02] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2020/10/07 04:53:02] [ info] [input:forward:forward.0] listening on 0.0.0.0:65011
[2020/10/07 04:53:02] [ info] [input:systemd:systemd.1] seek_cursor=s=2323c187d3894bdeaedc7b34732c3790;i=f8c... OK
[2020/10/07 04:54:02] [ info] [filter:throttle:throttle.0] 1602046442: limit is 40000.00 per 60s with window size of 5, current rate is: 0 per interval
[2020/10/07 04:54:02] [ info] [filter:kubernetes:kubernetes.1] https=1 host=kubernetes.default.svc.cluster.local port=443
[2020/10/07 04:54:02] [ info] [filter:kubernetes:kubernetes.1] local POD info OK
[2020/10/07 04:54:02] [ info] [filter:kubernetes:kubernetes.1] testing connectivity with API server...
[2020/10/07 04:54:03] [ info] [filter:kubernetes:kubernetes.1] API server connectivity OK
[2020/10/07 04:54:03] [ info] [http_server] listen iface=0.0.0.0 tcp_port=65012
[2020/10/07 04:54:03] [ info] [sp] stream processor started
[engine] caught signal (SIGSEGV)
````

or I saw few times (during start and even later during processing)
```
[2020/10/07 06:33:17] [ info] inotify_fs_add(): inode=15227055 watch_fd=124 name=/var/log/containers/eaf7ddfb8029510a7ad55d2e6337f07a6a2248ca-2661761879_argo_main-a8b4c28b37a1625423059c6ef572cff41c873818a9fa8338c8f21b42a25fc0c9.log
*** stack smashing detected ***: /bin/fluent-bit terminated
```

**Environment**
running in EKS, k8s v1.17
fluentbit 1.5.7 (custom build, base os image busybox:1.32.0-glibc-xenial), 

Dockerfile:
```
FROM amd64/ubuntu:xenial as builder

# Fluent Bit version
ENV FLB_MAJOR 1
ENV FLB_MINOR 5
ENV FLB_PATCH 7
ENV FLB_VERSION 1.5.7

ENV DEBIAN_FRONTEND noninteractive

ENV FLB_TARBALL http://github.com/fluent/fluent-bit/archive/v$FLB_VERSION.zip
RUN mkdir -p /fluent-bit/bin /fluent-bit/etc /fluent-bit/log /tmp/fluent-bit-master/

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      build-essential \
      cmake \
      make \
      wget \
      unzip \
      libssl-dev \
      libasl-dev \
      libsasl2-dev \
      pkg-config \
      libsystemd-dev \
      zlib1g-dev \
      ca-certificates \
      flex \
      bison \
      ca-certificates \
      zlib1g-dev \
      curl \
      tzdata \
      gnupg \
      dirmngr \
    && wget -O "/tmp/fluent-bit-${FLB_VERSION}.zip" ${FLB_TARBALL} \
    && cd /tmp && unzip "fluent-bit-$FLB_VERSION.zip" \
    && cd "fluent-bit-$FLB_VERSION"/build/ \
    && rm -rf /tmp/fluent-bit-$FLB_VERSION/build/*

WORKDIR /tmp/fluent-bit-$FLB_VERSION/build/
RUN cmake -DFLB_DEBUG=On \
          -DFLB_TRACE=Off \
          -DFLB_JEMALLOC=On \
          -DFLB_TLS=On \
          -DFLB_SHARED_LIB=Off \
          -DFLB_EXAMPLES=Off \
          -DFLB_HTTP_SERVER=On \
          -DFLB_IN_SYSTEMD=On \
          -DFLB_OUT_KAFKA=On ..

RUN make -j $(getconf _NPROCESSORS_ONLN)
RUN install bin/fluent-bit /fluent-bit/bin/

# Configuration files
COPY conf/fluent-bit.conf \
     conf/parsers.conf \
     conf/parsers_java.conf \
     conf/parsers_extra.conf \
     conf/parsers_openstack.conf \
     conf/parsers_cinder.conf \
     conf/plugins.conf \
     /fluent-bit/etc/

ADD rootfscopy.sh /usr/local/bin
RUN rootfscopy.sh \
        /etc/nsswitch.conf \
        /etc/ssl/certs/ca-certificates.crt \
        /usr/share/zoneinfo \
        /bin/bash \
        /usr/bin/curl \
        /lib/x86_64-linux-gnu/* \
        /fluent-bit/bin/fluent-bit \
        /fluent-bit/etc/*


ENV TINI_VERSION 0.18.0
RUN mkdir -p /rootfs/sbin && \
    wget -O /rootfs/sbin/tini https://github.com/krallin/tini/releases/download/v${TINI_VERSION}/tini && \
    wget -O tini.asc https://github.com/krallin/tini/releases/download/v${TINI_VERSION}/tini.asc && \
    gpg --batch --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 595E85A6B1B4779EA4DAAEC70B588DFF0527A9B7 && \
    gpg --batch --verify tini.asc /rootfs/sbin/tini && \
    chmod +x /rootfs/sbin/tini

FROM acme.azurecr.io/acme.io/busybox:1.32.0-glibc-xenial

EXPOSE 2020
COPY --from=0 /rootfs /

# Entry point
COPY entrypoint.sh /bin/
ENTRYPOINT ["/sbin/tini",  "--", "/bin/entrypoint.sh"]
CMD ["/bin/fluent-bit", "-c", "/fluent-bit/etc/fluent-bit.conf"]

```

**Comment by edsiper** [comment]
do you face the same issue when running our own Docker images ?

I see you are using a custom build and could potentially show a problem with the stack size and how the DNS responses are processed. 

Fluent Bit by default uses a stack size of 24KB for co-routines (when flushing data, connecting to a remote service), now inside a coroutine the stack size is fixed, and the DNS system resolver implementation uses the system call alloca(3) to store the DNS records, the problem with alloca(3) is that uses the stack space instead of the heap.

Try setting up ```coro_stack_size 65536``` in the service section and see if it mitigates the problem:

https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/configuration-file#config_section

**Comment by epcim** [comment]
@edsiper didnt solve the problem fully, but seems it crash less then before. Update: actually some of the restarts below were caused by liveness probe.

```
State | Restarts | Age
Running     0          19h
Running     0          19h
Running     0          19h
Running     1          19h
Running     15         19h
Running     0          19h
Running     0          19h
Running     0          19h
```

If it failed, then I only saw this in log (nothing else..)

```
*** stack smashing detected ***:
```

Any other suggestion, better value? If no further freq. crashes I will close on Monday.
(Thanks)

**Comment by edsiper** [comment]
are you able to detect any of your DNS endpoints that the list of target servers is very large ?

**Comment by epcim** [comment]
After the weekend.
```
Running     4          2d22h
Running     10         2d22h
Running     0          2d22h
Running     0          2d22h
Running     0          2d22h
Running     0          2d22h
Running     11         2d22h
Running     5          2d22h
```

espider, I dont think there is large list of DNS endpoints, it runs in isolated environment, reading logs from localhost sending logs to fluentd pod on the same cluster. What exactly you mean with DNS endpoints - the DNS servers? the servers fluentbit is talking to? Is it somehow affected if the fluentd pod changing it's IP on K8s cluster due it restarts?

How can I get more trace log from the crash that would uncover more details?

**Comment by epcim** [comment]
v1.6.0 and above seems to be ok

**Comment by edsiper** [comment]
are you ok with closing this issue ?

**Comment by epcim** [comment]
@edsiper yes, closing. Honestly on later versions issue does not repeat great!
