### ISSUE TITLE
Failed initialize filter parser.0 on hot reload

### ISSUE THREAD

**Issue by yujen77300** [fluent/fluent-bit#8275]
## Bug Report

**Describe the bug**
Failed initialize filter parser.0 when reloading via HTTP

**To Reproduce**
- Example log message if applicable:
```
[2023/12/12 08:45:06] [engine] caught signal (SIGHUP)
[2023/12/12 08:45:06] [ info] reloading instance pid=1 tid=0x7f4ba8961200
[2023/12/12 08:45:06] [ info] [reload] stop everything of the old context
[2023/12/12 08:45:06] [ warn] [engine] service will shutdown when all remaining tasks are flushed
[2023/12/12 08:45:07] [ info] [engine] service has stopped (0 pending tasks)
[2023/12/12 08:45:07] [ info] [output:stdout:stdout.0] thread worker #0 stopping...
[2023/12/12 08:45:07] [ info] [output:stdout:stdout.0] thread worker #0 stopped
[2023/12/12 08:45:07] [ info] [reload] start everything
[2023/12/12 08:45:07] [ info] [fluent bit] version=2.2.0, commit=db8487d123, pid=1
[2023/12/12 08:45:07] [ info] [storage] ver=1.5.1, type=memory, sync=normal, checksum=off, max_chunks_up=128
[2023/12/12 08:45:07] [ info] [cmetrics] version=0.6.4
[2023/12/12 08:45:07] [ info] [ctraces ] version=0.3.1
[2023/12/12 08:45:07] [ info] [input:http:http.0] initializing
[2023/12/12 08:45:07] [ info] [input:http:http.0] storage_strategy='memory' (memory only)
[2023/12/12 08:45:07] [error] [filter:parser:parser.0] requested parser 'json' not found
[2023/12/12 08:45:07] [error] [filter:parser:parser.0] Invalid 'parser'
[2023/12/12 08:45:07] [error] Failed initialize filter parser.0
[2023/12/12 08:45:07] [error] [engine] filter initialization failed
[2023/12/12 08:45:07] [error] [lib] backend failed
[2023/12/12 08:45:08] [error] [reload] loaded configuration contains error(s). Reloading is aborted
reloading is aborted and exit
```
- Steps to reproduce the problem:

1. `docker pull fluent/fluent-bit:2.2`
2. Create two files, fluent-bit.conf and parsers.conf.
fluent-bit.conf
```conf
[SERVICE]
    flush        1

    daemon       Off

    log_level    info

    parsers_file parsers.conf

    plugins_file plugins.conf

    # HTTP Server
    # ===========
    # Enable/Disable the built-in HTTP Server for metrics
    http_server  On
    http_listen  0.0.0.0
    http_port    2020
    Hot_Reload   On

[INPUT]
    name http
    listen 0.0.0.0
    port 8888
    Tag http.data

[FILTER]
    Name parser
    Match http.*
    Key_Name sql
    Parser json

[OUTPUT]
    name stdout
    match http.*
```
parsers.conf.
```conf
[PARSER]
    Name my_test
    Format regex
    Regex \/\*?(?<userId>[^,]*),(?<ip>[^,]*),(?<dbUser>[^,*]+)\*\/(?<sql_stmt>.*)

[PARSER]
    Name   json
    Format json
    Time_Key time
    Time_Format %d/%b/%Y:%H:%M:%S %z
```
3. Successfully start Fluent Bit with `docker run --rm --network=host -v /home/dbsecure/fluentbit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf -v /home/dbsecure/fluentbit/parsers.conf:/fluent-bit/etc/parsers.conf fluent/fluent-bit:2.2`  (alread)
```
[2023/12/12 08:43:01] [ info] [input:http:http.0] initializing
[2023/12/12 08:43:01] [ info] [input:http:http.0] storage_strategy='memory' (memory only)
[2023/12/12 08:43:01] [ info] [output:stdout:stdout.0] worker #0 started
[2023/12/12 08:43:01] [ info] [http_server] listen iface=0.0.0.0 tcp_port=2020
[2023/12/12 08:43:01] [ info] [sp] stream processor started
```
4. I didn.t change parsers.conf and run a reload with `curl -X POST -d '{}' localhost:2020/api/v2/reload`
5. `{"reload":"done","status":0}` but have error.

**Expected behavior**
Reload without errors.
I have referred to #6397 , #8240 , and changed the path to an absolute path, but the issue persists. However, I noticed that if I use other filters, such as 'modify,' there is no error.

**Your Environment**
* Version used: 2.2.0
* Configuration: Please refer to the 'Steps to reproduce the problem.'"
* Environment name and version (e.g. Kubernetes? What version?): docker run fluent/fluent-bit:2.2(image name)
* Server type and version:
* Operating System and version: Red Hat Enterprise Linux release 8.7 (Ootpa)
* Filters and plugins:

**Comment by patrick-stephens** [comment]
I think this is a duplicate of the known issue with working directory - specify the full path to the parsers file explicitly and confirm this resolves it?

**Comment by yujen77300** [comment]
Hi Patrick
Excuse me, may I ask where to obtain the full path? Since the Fluent Bit Docker image doesn't have a shell, I cannot use docker exec to enter the container. 
Isn't `/fluent-bit/etc/parsers.conf` the absolute path of the parse file? Because I can use the docker cp command to retrieve parsers.conf from `/fluent-bit/etc/parsers.conf` Thank you.

**Comment by patrick-stephens** [comment]
Indeed it is but you are specifying a custom parser and are mounting it in so the full path is your mount point as you say.

`-v /home/dbsecure/fluentbit/parsers.conf:/fluent-bit/etc/parsers.conf`

You are not specifying the full path in the config, only a relative one (there is no directory) so try with the full path.

`parsers_file /fluent-bit/etc/parsers.conf`

The issue is with relative paths going wrong on reload so using a full path should resolve it if this is the same issue that is resolved but not released yet.

**Comment by yujen77300** [comment]
Pat, thank you!  I have always paid attention to the path when using `docker run` but overlooked the path in conf.
Now it reload successfully ! Thank you very much for your detailed explanation !

**Comment by patrick-stephens** [comment]
Note this should be fixed in the next release I think, but in general it is good to be explicit.

**Comment by icy** [comment]
A quick note for who comes here for the same issue: The latest operator version 2.7.0 (https://github.com/fluent/fluent-operator/blob/v2.7.0/apis/fluentbit/v1alpha2/clusterfluentbitconfig_types.go#L172) still doesn't include this patch.
